// <auto-generated />
namespace jttt_hackathon.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class migracjarazpiec : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migracjarazpiec));
        
        string IMigrationMetadata.Id
        {
            get { return "201804191014142_migracjarazpiec"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
